name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Build documentation
        run: doxygen Doxyfile
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/html
          retention-days: 7
